"use strict";var n=require("fs"),e=require("path"),a=require("os"),t="hyperclick-nsis",i=t,o={schema:{pathToMakensis:{title:"Path to MakeNSIS",description:"Specify the full path to `makensis`",type:"string",default:"makensis",order:1},manageDependencies:{title:"Manage Dependencies",description:"When enabled, third-party dependencies will be installed automatically",type:"boolean",default:!0,order:2}},get:(n="")=>n?.length?atom.config.get(`${t}.${n}`):atom.config.get(`${t}`),migrate(n,e){if(atom.config.get(`${t}.${n}`)&&!atom.config.get(`${t}.${e}`)){try{atom.config.set(`${t}.${e}`,atom.config.get(`${t}.${n}`))}catch(n){return void atom.notifications.addWarning("Failed to migrate configuration, see console for details")}atom.config.unset(`${t}.${n}`)}},unset(n=""){const e=n?.length?`${t}.${n}`:t;atom.config.unset(e)},async open(n={}){n={pending:!0,searchAllPanes:!0,...n},await atom.workspace.open(`atom://config/packages/${t}`,n)}};const s=/(?:!include|LoadLanguageFile)\s+(?:"([^"]+)"|'([^']+)'|([^\r?\n]+$))/,r=["Colors.nsh","FileFunc.nsh","InstallOptions.nsh","LangFile.nsh","Library.nsh","LogicLib.nsh","Memento.nsh","MUI.nsh","MUI2.nsh","MultiUser.nsh","nsDialogs.nsh","Sections.nsh","StrFunc.nsh","TextFunc.nsh","UpgradeDLL.nsh","Util.nsh","VB6RunTime.nsh","VPatchLib.nsh","WinCore.nsh","WinMessages.nsh","WinVer.nsh","WordFunc.nsh","x64.nsh"],c=["Afrikaans","Albanian","Arabic","Armenian","Asturian","Basque","Belarusian","Bosnian","Breton","Bulgarian","Catalan","Corsican","Croatian","Czech","Danish","Dutch","English","Esperanto","Estonian","Farsi","Finnish","French","Galician","Georgian","German","Greek","Hebrew","Hungarian","Icelandic","Indonesian","Irish","Italian","Japanese","Korean","Kurdish","Latvian","Lithuanian","Luxembourgish","Macedonian","Malay","Mongolian","Norwegian","NorwegianNynorsk","Pashto","Polish","Portuguese","PortugueseBR","Romanian","Russian","ScotsGaelic","Serbian","SerbianLatin","SimpChinese","Slovak","Slovenian","Spanish","SpanishInternational","Swedish","Tatar","Thai","TradChinese","Turkish","Ukrainian","Uzbek","Vietnamese","Welsh"];async function l(n,i){const{nsisDir:s}=await Promise.resolve().then((function(){return require("./makensis-d7c052b7.js")})),l=o.get(`${t}.pathToMakensis`),h=l&&l.trim().length?{pathToMakensis:l}:{};let g;try{g=await s(h)}catch(n){return console.error(n),void atom.notifications.addError(`${t}`,{detail:"`makensis.exe` is not in your PATH [environmental variable](http://superuser.com/a/284351/195953)",dismissable:!0})}i.includes("${NSISDIR}")&&("win32"!==a.platform()&&i.includes("\\")&&(i=i.replace(/\\/g,"/")),i=i.replace(/\${NSISDIR}/gi,g));const{dir:u}=e.parse(n),{dir:p,ext:d,name:m}=e.parse(i);let f;f=e.isAbsolute(p)?e.join(p,m+d):r.indexOf(m+d)?e.join(g,"Include",m+d):c.indexOf(m)?e.join(g,"Contrib/Language files",m+d):e.join(u,p,m+d);return[f]}
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
function h(n,e){for(var a=0,t=e.length,i=n.length;a<t;a++,i++)n[i]=e[a];return n}var g=new(function(){function n(n){void 0===n&&(n={}),this.name=n.name,this.styleSheet="\n      background-color: "+(n.backgroundColor||"darkgrey")+";\n      border-radius: 2px;\n      color: "+(n.color||"white")+";\n      line-height: 1.5;\n      padding: 1px 4px;\n      text-shadow: 0 1px 0px rgba(0, 0, 0, 0.2);\n    "}return n.prototype.__console__=function(n){for(var e,a=[],t=1;t<arguments.length;t++)a[t-1]=arguments[t];(null===atom||void 0===atom?void 0:atom.inDevMode())&&(a.unshift("%c"+this.name+"%c",this.styleSheet,""),(e=window.console)[n].apply(e,a))},n.prototype.debug=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["debug"],n))},n.prototype.error=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["error"],n))},n.prototype.info=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["info"],n))},n.prototype.log=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["log"],n))},n.prototype.trace=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["trace"],n))},n.prototype.warn=function(){for(var n=[],e=0;e<arguments.length;e++)n[e]=arguments[e];this.__console__.apply(this,h(["warn"],n))},n}())({name:t,backgroundColor:"salmon"}),u={config:o.schema,async activate(){if(g.log("Activating package"),!0===atom.config.get(`${i}.manageDependencies`)){const{satisfyDependencies:n}=await Promise.resolve().then((function(){return require("./index-34bd97f5.js")})).then((function(n){return n.index}));n("hyperclick-nsis")}},deactivate(){g.log("Deactivating package")},getProvider:()=>({priority:1,grammarScopes:["source.nsis","source.nsis.bridle"],getSuggestionForWord(e,a,i){const{targetRange:o,targetFile:r}=function(n,e){const a=[[e.start.row,0],[e.end.row+1,0]];let t=null,i=null;return n.scanInBufferRange(s,a,(n=>{i=n.match[1]||n.match[2]||n.match[3],t=n.range,n.stop()})),{targetFile:i,targetRange:t}}(e,i);if(o&&r)return{range:o,async callback(){let a,i;try{i=await l(e.getPath(),r),a=await i.find((async e=>await n.promises.access(e,n.constants.F_OK)))}catch(n){return console.error(n),function(){const n=atom.notifications.addWarning(`${t}`,{detail:"Unable detect path for unsaved file. Please save this file and try again.",dismissable:!0,buttons:[{text:"Save As…",onDidClick:()=>{n.dismiss();const e=atom.workspace.getActiveTextEditor(),a=atom.views.getView(e);atom.commands.dispatch(a,"core:save-as")}},{text:"Cancel",onDidClick:()=>{n.dismiss()}}]})}()}if(a)return a=await n.promises.realpath(a),atom.workspace.open(a);atom.beep()}}}})};module.exports=u;
//# sourceMappingURL=index.js.map
